name: Playwright Tests

on:
  push:
    branches:
      - functional-tests-setup
  pull_request:
    branches:
      - functional-tests-setup

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Install Playwright browsers
      - name: Install Playwright Browsers
        run: npx playwright install

      # 5. Run Playwright tests
      - name: Run Playwright tests
        run: npx playwright test
